volumes:
  pg-data:

services:
  ganymede:
    image: ganymede
    ports:
      - 3000:3000
    volumes:
      - ./Ganymede.toml:/app/Ganymede.toml

  postgres:
    image: postgres:15.3
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: ganymede
      POSTGRES_HOST_AUTH_METHOD: trust
    volumes:
      - pg-data:/var/lib/postgresql/data
    ports:
        - 5432:5432
