name: Build

on: push

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.4
        with:
          submodules: true

      - name: Install tools
        run: sudo apt-get install g++-11 gcc-11 ninja-build

      - name: Install Conan
        run: |
          pip install conan
          conan config set general.revisions_enabled=1
          conan remote add davidbourgault https://artifactory.davidbourgault.ca/artifactory/api/conan/conan

      - name: Create directories
        run: mkdir build

      - name: Install Third Parties
        working-directory: build
        env:
          CC: gcc-11
          CXX: g++-11
        run: conan install .. --update --build=missing -s compiler.version=11 -s compiler.libcxx=libstdc++11 -s build_type=Release -r davidbourgault

      - name: Configure
        working-directory: build
        env:
          CC: gcc-11
          CXX: g++-11
        run: cmake .. -G Ninja -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=/usr

      - name: Build
        working-directory: build
        env:
          CC: gcc-11
          CXX: g++-11
        run: cmake --build . --config Release --parallel 2
